- job:
    name: cloudkitty-devstack-install
    parent: devstack
    description: |
      Job testing cloudkitty installation on devstack
    required-projects:
      - name: openstack/cloudkitty
      - name: openstack/python-cloudkittyclient
    roles:
      - zuul: openstack-infra/devstack
    timeout: 5400
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      devstack_plugins:
        cloudkitty: https://git.openstack.org/openstack/cloudkitty
      devstack_services:
        ck-api: true
        ck-proc: true
        horizon: false

- job:
    name: cloudkitty-tempest-full
    parent: devstack-tempest
    description: |
      Job testing cloudkitty installation on devstack and running tempest tests
    required-projects:
      - name: openstack/cloudkitty
      - name: openstack/cloudkitty-tempest-plugin
      - name: openstack/python-cloudkittyclient
    roles:
      - zuul: openstack-infra/devstack
    timeout: 5400
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      devstack_plugins:
        cloudkitty: https://git.openstack.org/openstack/cloudkitty
        cloudkitty-tempest-plugin: https://git.openstack.org/openstack/cloudkitty-tempest-plugin
      devstack_services:
        ck-api: true
        ck-proc: true
        horizon: false
        tempest: true
      tempest_concurrency: 1
      tempest_test_regex: cloudkitty_tempest_plugin.*
      tox_envlist: all
      devstack_localrc:
        TEMPEST_PLUGINS: /opt/stack/cloudkitty-tempest-plugin

- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - cloudkitty-tempest-full:
            voting: false
        - cloudkitty-devstack-install
    gate:
      queue: cloudkitty
      jobs:
        - cloudkitty-devstack-install
