- job:
    name: cloudkitty-tempest-full
    run: playbooks/cloudkitty-tempest-full/run.yaml
    post-run: playbooks/cloudkitty-tempest-full/post.yaml
    timeout: 5400
    parent: legacy-dsvm-base
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/cloudkitty
      - openstack/cloudkitty-tempest-plugin
      - openstack/python-cloudkittyclient

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - cloudkitty-tempest-full:
            voting: false
        - legacy-cloudkitty-dsvm-install
    gate:
      queue: cloudkitty
      jobs:
        - legacy-cloudkitty-dsvm-install
    post:
      jobs:
        - openstack-tox-cover
